export const site = {
  name: "Filosofia Aberta",
  baseUrl: "https://sidineyr.github.io/filosofia-aberta/",
  repository: "https://github.com/sidineyr/filosofia-aberta",
  author: "Sidiney Rodrigues",
  accessDate: "10 set. 2026",
  license: "CC BY 4.0",
};

export const periods = [
  {
    id: "antiga",
    title: "Filosofia Antiga",
    dates: "c. séc. VI a.C.–VI d.C.",
    description: "Natureza, linguagem, vida examinada, conhecimento, virtude e modos de viver.",
  },
  {
    id: "medieval",
    title: "Filosofia Medieval",
    dates: "séc. IV–XIV",
    description: "Tempo, criação, causalidade e as relações — tensas e produtivas — entre fé e razão.",
  },
  {
    id: "moderna",
    title: "Filosofia Moderna",
    dates: "séc. XVI–XVIII",
    description: "Método, experiência, liberdade, autoridade política e limites da razão.",
  },
  {
    id: "contemporanea",
    title: "Filosofia Contemporânea",
    dates: "séc. XIX–XXI",
    description: "História, crítica social, existência, linguagem, ciência, raça e poder.",
  },
];

export const institutions = [
  {
    category: "Universidade federal",
    name: "Universidade Federal de Santa Catarina — UFSC",
    url: "https://filosofia.ufsc.br/sobre-o-curso/",
    use: "Organização histórica da formação em Filosofia Antiga, Medieval, Moderna e Contemporânea.",
  },
  {
    category: "Universidade federal",
    name: "Universidade Federal de São Carlos — UFSCar",
    url: "https://www.prograd.ufscar.br/pt-br/cursos/cursos-oferecidos/filosofia",
    use: "Ênfase na História da Filosofia e acesso público a projetos pedagógicos e matrizes.",
  },
  {
    category: "Universidade federal",
    name: "Universidade Federal de Pelotas — UFPel",
    url: "https://institucional.ufpel.edu.br/disciplinas/cod/0730135",
    use: "Sequência de História da Filosofia Antiga, dos pré-socráticos ao neoplatonismo.",
  },
  {
    category: "Universidade federal",
    name: "Universidade Federal da Bahia — UFBA",
    url: "https://dpsofia.ufba.br/ementas/disciplinas-gerais",
    use: "Convivência entre História da Filosofia e componentes sistemáticos como lógica, ética e estética.",
  },
  {
    category: "Universidade estadual",
    name: "Universidade de São Paulo — USP",
    url: "https://filosofia.fflch.usp.br/graduacao",
    use: "Estudo aprofundado de autores e problemas, evitando panoramas apenas superficiais.",
  },
  {
    category: "Comunitária e confessional",
    name: "Pontifícia Universidade Católica de São Paulo — PUC-SP",
    url: "https://www.pucsp.br/graduacao/filosofia",
    use: "Pluralidade de tradições e presença de filosofia brasileira, latino-americana, africana, gênero e tecnologia.",
  },
  {
    category: "Faculdade privada comunitária/confessional",
    name: "Faculdade Jesuíta de Filosofia e Teologia — FAJE",
    url: "https://faculdadejesuita.edu.br/filosofia/",
    use: "Currículo público, bacharelado, licenciatura e pós-graduação numa instituição especializada em Filosofia e Teologia.",
  },
  {
    category: "Universidade privada confessional",
    name: "Universidade Presbiteriana Mackenzie — CEFT",
    url: "https://www.mackenzie.br/universidade/unidades-academicas/ceft",
    use: "Ensino, pesquisa e extensão reunidos no Centro de Educação, Filosofia e Teologia.",
  },
  {
    category: "Curso aberto internacional",
    name: "MIT OpenCourseWare — Classics of Western Philosophy",
    url: "https://ocw.mit.edu/courses/24-01-classics-of-western-philosophy-spring-2016/pages/syllabus/",
    use: "Leitura próxima de textos, exegese e análise em um curso integralmente aberto.",
  },
  {
    category: "Curso aberto internacional",
    name: "Open Yale Courses — Introduction to Political Philosophy",
    url: "https://oyc.yale.edu/political-science/plsc-114",
    use: "Sequência guiada de obras centrais da filosofia política com aulas e materiais abertos.",
  },
  {
    category: "Associação acadêmica",
    name: "Associação Nacional de Pós-Graduação em Filosofia — ANPOF",
    url: "https://anpof.org.br/",
    use: "Mapa vivo de programas, grupos de trabalho, publicações e debates filosóficos no Brasil.",
  },
];

export const modules = [
  {
    slug: "heraclito-mudanca",
    number: 1,
    period: "antiga",
    kicker: "Fragmentos e mudança",
    title: "Heráclito: como pensar o que muda?",
    shortTitle: "Heráclito e a mudança",
    duration: "25–35 min",
    difficulty: "inicial",
    question: "Como algo pode manter unidade se está sempre atravessado por diferenças e mudanças?",
    context: "Heráclito escreveu no final do século VI e início do V a.C. Sua obra não chegou inteira até nós: lemos fragmentos citados por autores posteriores. A numeração DK identifica a coleção de Diels e Kranz; ela não recompõe a ordem original do livro.",
    why: "O fragmento obriga a separar a autoridade de quem fala da razão que pode ser compartilhada. Ele também prepara a tensão entre mudança, unidade e conhecimento que atravessará Platão e Aristóteles.",
    concepts: ["logos", "unidade", "oposição", "mudança"],
    work: "Fragmentos, DK B50",
    passages: [
      {
        author: "Heráclito",
        work: "Fragmentos",
        locator: "fragmento 50; DK B50",
        quote: "É sábio escutar não a mim, mas ao logos, e concordar que todas as coisas são uma.",
        original: "It is wise to hearken, not to me, but to my Word, and to confess that all things are one.",
        edition: "Versão inglesa histórica reunida em Fragments of Heraclitus, Wikisource.",
        source: "Wikisource",
        url: "https://en.wikisource.org/wiki/Fragments_of_Heraclitus",
        translation: "Tradução de trabalho do Filosofia Aberta a partir da versão inglesa; logos foi preservado para não reduzi-lo a uma única palavra portuguesa.",
        rights: "Página em acesso livre; conteúdo da Wikisource sob CC BY-SA, com status próprio para a edição reproduzida.",
      },
    ],
    discussed: "A passagem desloca a atenção da pessoa de Heráclito para um logos que pode ser ouvido e examinado. A unidade mencionada não apaga as diferenças; é justamente a relação entre elas que vira problema.",
    misunderstanding: "“Tudo é um” não significa que todas as coisas sejam idênticas ou que a mudança seja ilusão. Leia a unidade como questão a explicar, não como resposta pronta.",
    guide: "Que tipo de unidade poderia incluir tensões sem eliminá-las?",
    reflection: [
      "O argumento dependeria da fama de Heráclito, ou o fragmento pede outro critério de autoridade?",
      "Pense em algo que permanece reconhecível enquanto muda. O que exatamente permanece?",
    ],
    readings: [
      {
        title: "Fragments of Heraclitus",
        author: "Heráclito",
        kind: "fonte primária",
        provider: "Wikisource",
        language: "inglês",
        time: "15 min (seleção)",
        difficulty: "intermediária",
        url: "https://en.wikisource.org/wiki/Fragments_of_Heraclitus",
        mission: "Leia os fragmentos 12 e 50; anote o que muda e o que conecta.",
        access: "acesso livre; veja a nota de direitos da edição",
      },
      {
        title: "Heraclitus",
        author: "Daniel W. Graham",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min (seções 1–3)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/heraclitus/",
        mission: "Confira por que fragmentos e testemunhos exigem cautela histórica.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Os sofistas deslocam parte da pergunta: se compartilhamos um mundo, como linguagem, persuasão e pontos de vista moldam o que aparece como verdadeiro?",
  },
  {
    slug: "protagoras-medida",
    number: 2,
    period: "antiga",
    kicker: "Sofistas e linguagem",
    title: "Protágoras: quem mede o que é verdadeiro?",
    shortTitle: "Protágoras e a medida",
    duration: "25–35 min",
    difficulty: "inicial",
    question: "Quando duas pessoas percebem a mesma situação de modos diferentes, existe uma medida comum?",
    context: "Muito do que sabemos sobre Protágoras vem de adversários e comentadores. A frase abaixo aparece em Platão, que a coloca no debate do Teeteto. Ela é testemunho antigo de Protágoras, não uma página preservada de seu próprio livro.",
    why: "A passagem abre problemas sobre percepção, relatividade, educação e persuasão. Também ensina uma regra do projeto: uma frase pode ser autêntica como testemunho sem nos dar acesso neutro ao autor.",
    concepts: ["medida", "percepção", "relativismo", "testemunho"],
    work: "Platão, Teeteto 152a (testemunho de Protágoras)",
    passages: [
      {
        author: "Protágoras, transmitido por Platão",
        work: "Teeteto",
        locator: "152a",
        quote: "O ser humano é a medida de todas as coisas: das que são, que são; das que não são, que não são.",
        original: "Man, he says, is the measure of all things, of the existence of the things that are and the non-existence of the things that are not.",
        edition: "Tradução inglesa histórica de Benjamin Jowett, The Internet Classics Archive.",
        source: "The Internet Classics Archive — MIT",
        url: "https://classics.mit.edu/Plato/theatu.html",
        translation: "Tradução de trabalho do projeto a partir de Jowett; “ser humano” evita tomar man como referência apenas masculina.",
        rights: "Acesso gratuito à tradução histórica; condições e direitos permanecem os da fonte.",
      },
    ],
    discussed: "No diálogo, Sócrates relaciona a tese à percepção: o vento pode parecer frio a uma pessoa e não frio a outra. A pergunta é se aparecer e ser coincidem para cada sujeito.",
    misunderstanding: "A frase não prova sozinha que “toda opinião vale o mesmo”. O próprio Platão testa consequências e dificuldades; é preciso acompanhar o argumento, não transformar o fragmento em slogan.",
    guide: "Se cada pessoa é medida, como Protágoras ainda poderia ensinar alguém a julgar melhor?",
    reflection: [
      "Dê um exemplo em que discordância de percepção não seja simples erro de uma das partes.",
      "Que critérios usamos quando precisamos decidir coletivamente apesar de perspectivas diferentes?",
    ],
    readings: [
      {
        title: "Theaetetus, 151d–160e",
        author: "Platão",
        kind: "fonte primária em contexto",
        provider: "The Internet Classics Archive — MIT",
        language: "inglês",
        time: "20 min",
        difficulty: "intermediária",
        url: "https://classics.mit.edu/Plato/theatu.html",
        mission: "Comece em 151d e acompanhe o exemplo do vento antes de avaliar a tese.",
        access: "acesso gratuito; tradução histórica",
      },
      {
        title: "The Sophists",
        author: "C. C. W. Taylor e Mi-Kyoung Lee",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min (introdução e Protágoras)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/sophists/",
        mission: "Compare a imagem platônica dos sofistas com o contexto educacional do século V a.C.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Sócrates compartilha com os sofistas a Atenas do debate público, mas Platão o apresenta interrogando a pretensão de saber em vez de vender uma técnica de êxito.",
  },
  {
    slug: "socrates-vida-examinada",
    number: 3,
    period: "antiga",
    kicker: "Sócrates via Platão",
    title: "Sócrates: por que examinar a própria vida?",
    shortTitle: "Sócrates e a vida examinada",
    duration: "30–40 min",
    difficulty: "inicial",
    question: "O que torna uma vida digna de ser vivida — e que papel o exame de si tem nisso?",
    context: "Sócrates não deixou escritos. A Apologia é uma obra de Platão que representa sua defesa no julgamento de 399 a.C.; não é transcrição neutra. Por isso distinguimos o Sócrates histórico, o personagem platônico e a interpretação do leitor.",
    why: "O trecho une filosofia, cuidado de si, diálogo e responsabilidade pública. Lido no contexto, ele é mais exigente que a frase famosa isolada.",
    concepts: ["exame", "cuidado da alma", "virtude", "ignorância"],
    work: "Platão, Apologia 38a",
    passages: [
      {
        author: "Platão, representando Sócrates",
        work: "Apologia de Sócrates",
        locator: "38a",
        quote: "Uma vida sem exame não é vivível para um ser humano.",
        original: "The unexamined life is not worth living.",
        edition: "Texto grego e tradução inglesa de Harold North Fowler no Perseus; comparação com Benjamin Jowett.",
        source: "Perseus Digital Library",
        url: "https://www.perseus.tufts.edu/hopper/text?doc=plat.+apol.+38a",
        translation: "Tradução de trabalho mais literal. A formulação tradicional “não vale a pena ser vivida” continua útil, mas já interpreta o caráter de “não vivível”.",
        rights: "Acesso gratuito; edição e tradução identificadas no catálogo Perseus.",
      },
    ],
    discussed: "Antes da frase, Sócrates afirma que conversar diariamente sobre virtude e examinar a si e aos outros é um grande bem. A sentença encerra uma defesa de prática filosófica, não uma recomendação de introspecção solitária.",
    misunderstanding: "Examinar não é ruminar indefinidamente nem supor que toda escolha precise de certeza absoluta. No diálogo, o exame acontece com razões, perguntas e interlocutores.",
    guide: "Que diferença há entre pensar muito sobre si e submeter uma crença a exame?",
    reflection: [
      "Qual crença sua mudaria se você precisasse oferecer razões públicas para ela?",
      "A vida examinada pode se tornar arrogante? O que a ignorância socrática acrescenta como limite?",
    ],
    readings: [
      {
        title: "Apologia 21a–23b, 29d–30b e 38a",
        author: "Platão",
        kind: "fonte primária",
        provider: "Perseus Digital Library — Tufts University",
        language: "grego e inglês",
        time: "20 min",
        difficulty: "inicial–intermediária",
        url: "https://www.perseus.tufts.edu/hopper/text?doc=plat.+apol.+38a",
        mission: "Relacione oráculo, cuidado da alma e vida examinada; não leia 38a sozinho.",
        access: "acesso gratuito; edição e tradução identificadas",
      },
      {
        title: "Socrates",
        author: "Debra Nails e S. Sara Monoson",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (seções 1–3)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/socrates/",
        mission: "Identifique por que testemunhos divergentes criam o “problema socrático”.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
      {
        title: "Apology, tradução de Benjamin Jowett",
        author: "Platão",
        kind: "tradução histórica complementar",
        provider: "Project Gutenberg",
        language: "inglês",
        time: "45 min",
        difficulty: "intermediária",
        url: "https://www.gutenberg.org/ebooks/1656",
        mission: "Compare a redação de 38a com o Perseus e registre uma diferença tradutória.",
        access: "domínio público nos EUA; confira a jurisdição local",
      },
    ],
    relation: "Platão transforma a figura de Sócrates em interlocutor de obras que ampliam o exame para conhecimento, justiça, educação e organização da cidade.",
  },
  {
    slug: "platao-caverna",
    number: 4,
    period: "antiga",
    kicker: "Conhecimento e educação",
    title: "Platão: o que a caverna ensina sobre aprender?",
    shortTitle: "Platão e a caverna",
    duration: "30–40 min",
    difficulty: "inicial",
    question: "Educar é transmitir informações ou reorientar a maneira como alguém vê?",
    context: "A imagem da caverna aparece no livro VII da República, após as analogias do Sol e da Linha. Sócrates pede a Glauco que imagine prisioneiros, sombras, libertação e retorno. A cena investiga educação e conhecimento dentro de uma discussão maior sobre justiça e governo.",
    why: "A alegoria ajuda a pensar aparência, formação e resistência à mudança. Seu sentido, porém, depende do movimento inteiro — inclusive o retorno à caverna.",
    concepts: ["aparência", "conhecimento", "educação", "retorno"],
    work: "Platão, República VII, 514a–521b",
    passages: [
      {
        author: "Platão",
        work: "República",
        locator: "VII, 514a–515a",
        quote: "Imagina seres humanos vivendo numa morada subterrânea, em forma de caverna, com uma entrada aberta à luz em toda a sua largura.",
        original: "Behold! human beings living in an underground den, which has a mouth open towards the light and reaching all along the den.",
        edition: "Tradução inglesa histórica de Benjamin Jowett, The Internet Classics Archive.",
        source: "The Internet Classics Archive — MIT",
        url: "https://classics.mit.edu/Plato/republic.8.vii.html",
        translation: "Tradução de trabalho do projeto a partir de Jowett.",
        rights: "Acesso gratuito à tradução histórica; condições e direitos permanecem os da fonte.",
      },
    ],
    discussed: "A abertura constrói uma situação de aprendizagem condicionada: os prisioneiros tomam sombras por realidade porque sua experiência foi limitada. A libertação dói, exige tempo e não termina em contemplação privada.",
    misunderstanding: "A caverna não autoriza chamar qualquer discordante de “prisioneiro”. Quem saiu deve retornar, explicar e assumir responsabilidade; a imagem também interroga a arrogância de quem se julga esclarecido.",
    guide: "Por que a libertação começa com desconforto, e por que o retorno faz parte da educação?",
    reflection: [
      "Qual hábito de atenção pode fazer uma aparência parecer toda a realidade?",
      "Como distinguir educação de imposição quando alguém afirma estar nos conduzindo para fora da caverna?",
    ],
    readings: [
      {
        title: "Republic, Book VII",
        author: "Platão",
        kind: "fonte primária",
        provider: "The Internet Classics Archive — MIT",
        language: "inglês",
        time: "30 min (514a–521b)",
        difficulty: "intermediária",
        url: "https://classics.mit.edu/Plato/republic.8.vii.html",
        mission: "Marque quatro movimentos: prisão, libertação, visão e retorno.",
        access: "acesso gratuito; tradução histórica",
      },
      {
        title: "Plato’s Ethics and Politics in The Republic",
        author: "Eric Brown",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min (introdução)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/plato-ethics-politics/",
        mission: "Localize a caverna dentro do problema da justiça, não como alegoria isolada.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Aristóteles estudará com Platão, mas buscará explicar a vida boa a partir das atividades, hábitos e fins próprios de seres humanos concretos.",
  },
  {
    slug: "aristoteles-vida-boa",
    number: 5,
    period: "antiga",
    kicker: "Ética e prática",
    title: "Aristóteles: a felicidade é sentimento ou atividade?",
    shortTitle: "Aristóteles e a vida boa",
    duration: "30–40 min",
    difficulty: "intermediária",
    question: "Uma vida boa depende de sentir-se bem ou de exercer bem certas capacidades ao longo do tempo?",
    context: "No livro I da Ética a Nicômaco, Aristóteles procura o fim último das ações humanas. Em I.7, formula o chamado argumento da função: pergunta o que caracteriza a atividade humana e liga o bem ao exercício da razão segundo a virtude.",
    why: "O trecho desloca felicidade de um estado passageiro para uma forma de atividade. Isso permite discutir hábitos, caráter, circunstâncias e duração de uma vida.",
    concepts: ["eudaimonia", "atividade", "virtude", "função"],
    work: "Ética a Nicômaco I.7, 1097b22–1098a20",
    passages: [
      {
        author: "Aristóteles",
        work: "Ética a Nicômaco",
        locator: "I.7, 1098a16–18",
        quote: "O bem humano resulta ser uma atividade da alma de acordo com a virtude; e, se há várias virtudes, de acordo com a melhor e mais completa.",
        original: "Human good turns out to be activity of soul in accordance with virtue, and if there are more than one virtue, in accordance with the best and most complete.",
        edition: "Tradução inglesa de W. D. Ross, disponibilizada pelo The Internet Classics Archive.",
        source: "The Internet Classics Archive — MIT",
        url: "https://classics.mit.edu/Aristotle/nicomachaen.1.i.html",
        translation: "Tradução de trabalho do projeto a partir de Ross; eudaimonia não se reduz a “estar feliz”.",
        rights: "Acesso gratuito à tradução histórica; condições e direitos permanecem os da fonte.",
      },
    ],
    discussed: "Aristóteles não define o bem como posse da virtude, mas como atividade conforme a virtude. Ele acrescenta “em uma vida completa”, impedindo que um instante isolado decida toda a avaliação.",
    misunderstanding: "O argumento não diz que toda pessoa tem uma profissão natural fixa. “Função” designa aqui uma atividade característica usada para investigar o bem humano.",
    guide: "Por que possuir uma capacidade não basta, se ela nunca é exercida?",
    reflection: [
      "Que diferença há entre ter uma virtude e agir virtuosamente numa situação difícil?",
      "Bens externos e sorte tornam a ética aristotélica menos exigente ou mais realista?",
    ],
    readings: [
      {
        title: "Nicomachean Ethics, Book I",
        author: "Aristóteles",
        kind: "fonte primária",
        provider: "The Internet Classics Archive — MIT",
        language: "inglês",
        time: "35 min",
        difficulty: "intermediária",
        url: "https://classics.mit.edu/Aristotle/nicomachaen.1.i.html",
        mission: "Leia I.1, I.4 e I.7; acompanhe como a pergunta pelo fim se torna pergunta pela atividade.",
        access: "acesso gratuito; tradução histórica de W. D. Ross",
      },
      {
        title: "Aristotle’s Ethics",
        author: "Richard Kraut",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (seções 1–3)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/aristotle-ethics/",
        mission: "Compare eudaimonia, virtude e razão prática sem traduzir tudo por “felicidade”.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Epicuro e Epicteto também perguntam como viver, mas em escolas que transformam filosofia em exercício cotidiano diante do desejo, do medo e do acaso.",
  },
  {
    slug: "helenismo-cuidado",
    number: 6,
    period: "antiga",
    kicker: "Epicurismo e estoicismo",
    title: "Epicuro e Epicteto: o que está em nossas mãos?",
    shortTitle: "Epicuro, Epicteto e o cuidado",
    duration: "35–45 min",
    difficulty: "inicial",
    question: "Como cuidar da vida quando desejos, perdas e acontecimentos não obedecem à nossa vontade?",
    context: "As escolas helenísticas tratam filosofia como investigação e exercício de vida. Epicuro escreve a Meneceu sobre prazer, medo e sabedoria; séculos depois, o Manual reúne ensinamentos estoicos de Epicteto registrados por Arriano.",
    why: "Ler os dois lado a lado mostra convergências práticas sem apagar divergências: Epicuro analisa desejos e prazeres; Epicteto começa distinguindo juízos e ações sob nosso encargo do que não controlamos.",
    concepts: ["prazer", "desejo", "juízo", "controle"],
    work: "Epicuro, Carta a Meneceu 122; Epicteto, Manual 1",
    passages: [
      {
        author: "Epicuro",
        work: "Carta a Meneceu",
        locator: "122",
        quote: "Ninguém, sendo jovem, adie filosofar; nem, sendo velho, se canse de filosofar.",
        original: "Let no one be slow to seek wisdom when he is young nor weary in the search thereof when he is grown old.",
        edition: "Tradução inglesa de Robert Drew Hicks, The Internet Classics Archive.",
        source: "The Internet Classics Archive — MIT",
        url: "https://classics.mit.edu/Epicurus/menoec.html",
        translation: "Tradução de trabalho do projeto a partir de Hicks.",
        rights: "Acesso gratuito à tradução histórica; condições e direitos permanecem os da fonte.",
      },
      {
        author: "Epicteto",
        work: "Manual",
        locator: "1",
        quote: "Algumas coisas dependem de nós; outras não dependem de nós.",
        original: "Some things are in our control and others not.",
        edition: "Tradução inglesa de Elizabeth Carter, The Internet Classics Archive.",
        source: "The Internet Classics Archive — MIT",
        url: "https://classics.mit.edu/Epictetus/epicench.html",
        translation: "Tradução de trabalho do projeto a partir de Carter; “dependem de nós” traduz o campo do que está sob nosso encargo, não poder ilimitado.",
        rights: "Acesso gratuito à tradução histórica; condições e direitos permanecem os da fonte.",
      },
    ],
    discussed: "Epicuro apresenta a filosofia como cuidado possível em qualquer idade. Epicteto inicia por uma distinção prática: opiniões, impulsos e escolhas são nossos; corpo, reputação e cargos não o são do mesmo modo.",
    misunderstanding: "Epicurismo não é busca de excesso, e estoicismo não é ausência de sentimentos. Ambos pedem trabalho racional sobre desejos e juízos, não anestesia emocional.",
    guide: "A distinção entre o que depende e não depende de nós ajuda a agir ou pode virar desculpa para omissão?",
    reflection: [
      "Escolha uma preocupação atual e separe nela ação possível, condição externa e julgamento.",
      "Que desejos produzem tranquilidade quando satisfeitos — e quais apenas ampliam a falta?",
    ],
    readings: [
      {
        title: "Letter to Menoeceus",
        author: "Epicuro",
        kind: "fonte primária",
        provider: "The Internet Classics Archive — MIT",
        language: "inglês",
        time: "12 min",
        difficulty: "inicial",
        url: "https://classics.mit.edu/Epicurus/menoec.html",
        mission: "Marque as definições de prazer e os tipos de desejo; não pare na abertura.",
        access: "acesso gratuito; tradução de Robert Drew Hicks",
      },
      {
        title: "The Enchiridion",
        author: "Epicteto",
        kind: "fonte primária",
        provider: "The Internet Classics Archive — MIT",
        language: "inglês",
        time: "25 min",
        difficulty: "inicial",
        url: "https://classics.mit.edu/Epictetus/epicench.html",
        mission: "Leia 1, 5 e 8; teste a diferença entre acontecimento e juízo.",
        access: "acesso gratuito; tradução de Elizabeth Carter",
      },
      {
        title: "Ancient Ethical Theory",
        author: "Richard Parry e Harald Thorsrud",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min (helenismo)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/ethics-ancient/",
        mission: "Situe as duas escolas na questão antiga da vida boa.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "O neoplatonismo transmitirá e transformará temas gregos no mundo tardo-antigo. Agostinho os encontra dentro de uma investigação cristã da memória, da criação e do tempo.",
  },
  {
    slug: "agostinho-tempo",
    number: 7,
    period: "medieval",
    kicker: "Interioridade e tempo",
    title: "Agostinho: o que é o tempo?",
    shortTitle: "Agostinho e o tempo",
    duration: "30–40 min",
    difficulty: "intermediária",
    question: "Como medimos passado e futuro se o primeiro já não é e o segundo ainda não é?",
    context: "No livro XI das Confissões, Agostinho interpreta a criação e pergunta pelo tempo. A investigação ocorre em forma de oração, argumento e exame da experiência: memória, atenção e expectativa entram no problema.",
    why: "O trecho começa com uma perplexidade honesta e mostra a filosofia trabalhando a partir do que parece familiar. Ele também desfaz a ideia de que a filosofia medieval apenas repete respostas religiosas.",
    concepts: ["tempo", "memória", "atenção", "criação"],
    work: "Confissões XI.14–28",
    passages: [
      {
        author: "Agostinho de Hipona",
        work: "Confissões",
        locator: "XI.14.17",
        quote: "Que é, pois, o tempo? Se ninguém me pergunta, eu sei; se quero explicá-lo a quem pergunta, não sei.",
        original: "What, then, is time? If no one ask of me, I know; if I wish to explain to him who asks, I know not.",
        edition: "Tradução inglesa de J. G. Pilkington na coleção Nicene and Post-Nicene Fathers, New Advent.",
        source: "New Advent",
        url: "https://www.newadvent.org/fathers/110111.htm",
        translation: "Tradução de trabalho do projeto a partir de Pilkington; confira uma edição portuguesa antes de citar academicamente.",
        rights: "Acesso gratuito; a edição inglesa histórica e o site têm condições próprias.",
      },
    ],
    discussed: "Agostinho não termina na confissão de ignorância. Ele examina como falamos de três tempos e propõe pensar presente do passado, do presente e do futuro na memória, atenção e expectativa.",
    misunderstanding: "A frase não celebra o mistério para impedir a investigação. Ela inicia uma análise longa: reconhecer a dificuldade é método, não desistência.",
    guide: "Quando medimos uma duração, medimos o acontecimento ou alguma marca que ele deixa na consciência?",
    reflection: [
      "Tente apontar onde está o passado de uma frase logo depois de pronunciá-la.",
      "Memória e expectativa distorcem o tempo ou são condições para experimentá-lo?",
    ],
    readings: [
      {
        title: "Confessions, Book XI",
        author: "Agostinho de Hipona",
        kind: "fonte primária",
        provider: "New Advent",
        language: "inglês",
        time: "35 min (capítulos 14–28)",
        difficulty: "intermediária",
        url: "https://www.newadvent.org/fathers/110111.htm",
        mission: "Siga as mudanças entre tempo do mundo, linguagem e experiência interior.",
        access: "acesso gratuito; tradução histórica identificada",
      },
      {
        title: "Saint Augustine",
        author: "Christian Tornau",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (vida e mente)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/augustine/",
        mission: "Localize a análise do tempo no projeto filosófico mais amplo de Agostinho.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Tomás de Aquino retomará problemas antigos e cristãos com outro método: questões, objeções, respostas e réplicas organizam uma investigação sistemática.",
  },
  {
    slug: "tomas-causalidade",
    number: 8,
    period: "medieval",
    kicker: "Razão, objeção e resposta",
    title: "Tomás de Aquino: explicar é encontrar uma causa?",
    shortTitle: "Tomás de Aquino e a causalidade",
    duration: "35–45 min",
    difficulty: "intermediária",
    question: "Até onde uma explicação causal pode regressar — e o que seria necessário para ela começar?",
    context: "A Suma Teológica organiza cada artigo como disputa: pergunta, objeções, argumento em contrário, resposta e réplicas. Na questão 2, artigo 3, Tomás apresenta cinco vias; o trecho abaixo abre a primeira, a partir da mudança.",
    why: "Além do tema teológico, o texto ensina a ler uma arquitetura argumentativa. A pergunta útil não é apenas “concordo?”, mas “quais premissas fazem a inferência funcionar?”.",
    concepts: ["movimento", "causa", "regresso", "objeção"],
    work: "Suma Teológica I, questão 2, artigo 3",
    passages: [
      {
        author: "Tomás de Aquino",
        work: "Suma Teológica",
        locator: "I, q. 2, a. 3, resposta",
        quote: "É certo, e evidente aos sentidos, que neste mundo algumas coisas estão em movimento. Ora, tudo o que se move é movido por outro.",
        original: "It is certain, and evident to our senses, that in the world some things are in motion. Now whatever is in motion is put in motion by another.",
        edition: "Tradução dos Fathers of the English Dominican Province, disponibilizada pelo New Advent.",
        source: "New Advent",
        url: "https://www.newadvent.org/summa/1002.htm",
        translation: "Tradução de trabalho do projeto a partir da edição inglesa; “movimento” inclui mudança, não apenas deslocamento físico.",
        rights: "Acesso gratuito; tradução e site têm condições próprias.",
      },
    ],
    discussed: "A primeira via parte da passagem de potência a ato. Tomás argumenta que algo não pode, sob o mesmo aspecto, atualizar a si próprio e rejeita um regresso infinito nessa ordem de dependência.",
    misunderstanding: "A primeira via não é simplesmente “tudo tem uma causa”. O argumento distingue tipos de causa e depende de conceitos aristotélicos de potência e ato.",
    guide: "Que diferença existe entre uma série de acontecimentos no passado e uma série de dependências que operam agora?",
    reflection: [
      "Reconstrua a primeira via em três premissas e uma conclusão; onde está o passo mais discutível?",
      "Por que começar pelas objeções pode tornar uma posição mais, e não menos, rigorosa?",
    ],
    readings: [
      {
        title: "Summa Theologiae I, q. 2",
        author: "Tomás de Aquino",
        kind: "fonte primária",
        provider: "New Advent",
        language: "inglês",
        time: "25 min",
        difficulty: "intermediária–avançada",
        url: "https://www.newadvent.org/summa/1002.htm",
        mission: "Separe objeções, resposta e réplicas; não confunda a voz do objetor com a de Tomás.",
        access: "acesso gratuito; tradução histórica identificada",
      },
      {
        title: "Saint Thomas Aquinas",
        author: "Robert Pasnau",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (metafísica e Deus)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/aquinas/",
        mission: "Revise potência, ato e causalidade antes de avaliar as vias.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Descartes herda questões escolásticas, mas dramatiza uma nova exigência de fundamento: suspender crenças para testar o que resiste à dúvida.",
  },
  {
    slug: "descartes-duvida",
    number: 9,
    period: "moderna",
    kicker: "Método e certeza",
    title: "Descartes: o que resiste à dúvida?",
    shortTitle: "Descartes e a dúvida",
    duration: "30–40 min",
    difficulty: "inicial–intermediária",
    question: "É possível duvidar de tudo sem perder o próprio ato de duvidar?",
    context: "Nas Meditações, Descartes pede ao leitor que realize um exercício em primeira pessoa. Depois de ampliar a dúvida na primeira meditação, procura na segunda algo que permaneça verdadeiro mesmo se houver engano radical.",
    why: "O cogito não é uma senha decorada; é um desempenho argumentativo. A leitura mostra por que a existência do pensamento é reconhecida no próprio ato em que se tenta negá-la.",
    concepts: ["dúvida metódica", "cogito", "certeza", "pensamento"],
    work: "Meditações sobre Filosofia Primeira, II",
    passages: [
      {
        author: "René Descartes",
        work: "Meditações sobre Filosofia Primeira",
        locator: "Meditação II; AT VII 25",
        quote: "Eu sou, eu existo: isto é necessariamente verdadeiro sempre que o enuncio ou o concebo em meu espírito.",
        original: "I am, I exist, is necessarily true whenever it is put forward by me or conceived in my mind.",
        edition: "Edição inglesa em domínio público transcrita pela Wikisource; referência padrão AT VII 25.",
        source: "Wikisource",
        url: "https://en.wikisource.org/wiki/Meditations_on_First_Philosophy/Meditation_II",
        translation: "Tradução de trabalho do projeto. A frase da Meditação não tem exatamente a forma latina cogito, ergo sum.",
        rights: "Página em acesso livre; verifique na própria edição o status da tradução reproduzida.",
      },
    ],
    discussed: "A certeza vale toda vez que o pensamento é efetivamente realizado. Descartes então pergunta o que é esse “eu” e responde inicialmente: uma coisa que pensa — duvida, entende, afirma, nega, quer, imagina e sente.",
    misunderstanding: "O argumento não deduz a existência a partir de uma premissa geral “tudo o que pensa existe”. Na meditação, a certeza aparece no ato, antes de uma teoria completa do eu.",
    guide: "A certeza do cogito prova a existência de um corpo ou apenas de pensamento enquanto ocorre?",
    reflection: [
      "Que crenças a dúvida cartesiana suspende, e quais capacidades ela ainda usa para suspender?",
      "Uma certeza momentânea basta para reconstruir conhecimento duradouro?",
    ],
    readings: [
      {
        title: "Meditation II",
        author: "René Descartes",
        kind: "fonte primária",
        provider: "Wikisource",
        language: "inglês",
        time: "20 min",
        difficulty: "intermediária",
        url: "https://en.wikisource.org/wiki/Meditations_on_First_Philosophy/Meditation_II",
        mission: "Sublinhe cada capacidade incluída no que Descartes chama “pensar”.",
        access: "acesso livre; consulte o status da edição",
      },
      {
        title: "Descartes’ Epistemology",
        author: "Lex Newman",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (dúvida e cogito)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/descartes-epistemology/",
        mission: "Diferencie dúvida metódica, ceticismo e a função do cogito.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Hobbes, Locke e Hume rejeitarão ou reformularão partes do racionalismo cartesiano, perguntando como experiência, hábito e vida política estruturam nossas crenças.",
  },
  {
    slug: "hobbes-locke-hume",
    number: 10,
    period: "moderna",
    kicker: "Experiência e política",
    title: "Hobbes, Locke e Hume: de onde vêm ordem e expectativa?",
    shortTitle: "Hobbes, Locke e Hume",
    duration: "45–60 min",
    difficulty: "intermediária",
    question: "O que sustenta a ordem política e por que esperamos que o futuro se pareça com o passado?",
    context: "Este módulo aproxima três problemas, sem fundir os autores: Hobbes imagina insegurança sem poder comum; Locke descreve liberdade e igualdade naturais; Hume examina por que repetição produz expectativa causal.",
    why: "O contraste mostra que “empirismo britânico” não é uma doutrina única. Política, mente e conhecimento recebem argumentos distintos, que devem ser comparados por suas premissas.",
    concepts: ["estado de natureza", "igualdade", "experiência", "costume"],
    work: "Leviatã XIII; Segundo Tratado II.4; Investigação V.36",
    passages: [
      {
        author: "Thomas Hobbes",
        work: "Leviatã",
        locator: "parte I, capítulo XIII",
        quote: "E a vida do ser humano é solitária, pobre, sórdida, brutal e curta.",
        original: "And the life of man, solitary, poore, nasty, brutish, and short.",
        edition: "Texto inglês de 1651 transcrito pelo Project Gutenberg, eBook 3207.",
        source: "Project Gutenberg",
        url: "https://www.gutenberg.org/cache/epub/3207/pg3207-images.html",
        translation: "Tradução de trabalho do projeto; o trecho descreve uma condição sem segurança comum, não toda convivência humana observada.",
        rights: "Domínio público nos EUA segundo o Project Gutenberg; confira a jurisdição local.",
      },
      {
        author: "John Locke",
        work: "Segundo Tratado sobre o Governo",
        locator: "livro II, capítulo II, §4",
        quote: "Um estado de perfeita liberdade [...] e também um estado de igualdade, em que todo poder e jurisdição são recíprocos.",
        original: "A state of perfect freedom [...] A state also of equality, wherein all the power and jurisdiction is reciprocal.",
        edition: "Edição inglesa histórica disponibilizada pela Wikisource.",
        source: "Wikisource",
        url: "https://en.wikisource.org/wiki/Two_Treatises_of_Government/Book_II/Chapter_II",
        translation: "Tradução de trabalho do projeto; as omissões estão indicadas por colchetes.",
        rights: "Página em acesso livre; verifique o status específico da edição reproduzida.",
      },
      {
        author: "David Hume",
        work: "Investigação sobre o Entendimento Humano",
        locator: "seção V, parte I, §36",
        quote: "Todas as inferências da experiência são efeitos do costume, não do raciocínio.",
        original: "All inferences from experience, therefore, are effects of custom, not of reasoning.",
        edition: "Edição de L. A. Selby-Bigge, Project Gutenberg, eBook 9662.",
        source: "Project Gutenberg",
        url: "https://www.gutenberg.org/cache/epub/9662/pg9662-images.html",
        translation: "Tradução de trabalho do projeto a partir do texto inglês.",
        rights: "Domínio público nos EUA segundo o Project Gutenberg; confira a jurisdição local.",
      },
    ],
    discussed: "Hobbes liga insegurança a ausência de garantia comum; Locke usa igualdade e liberdade para limitar poder; Hume localiza no costume, não numa prova racional, a passagem de repetições passadas a expectativas futuras.",
    misunderstanding: "Não leia os três como uma sequência de “respostas melhores”. Eles respondem a perguntas diferentes e usam cenários teóricos, análise conceitual e observação da mente de maneiras distintas.",
    guide: "O costume que estabiliza expectativas na natureza se parece com o costume que estabiliza instituições políticas?",
    reflection: [
      "Que diferença entre Hobbes e Locke aparece já na maneira de descrever o estado de natureza?",
      "Se Hume tem razão, reconhecer que a expectativa nasce do hábito a torna irracional?",
    ],
    readings: [
      {
        title: "An Enquiry Concerning Human Understanding, IV–V",
        author: "David Hume",
        kind: "fonte primária",
        provider: "Project Gutenberg",
        language: "inglês",
        time: "35 min",
        difficulty: "intermediária",
        url: "https://www.gutenberg.org/ebooks/9662",
        mission: "Reconstrua a passagem experiência → repetição → expectativa → crença.",
        access: "domínio público nos EUA; confira a jurisdição local",
      },
      {
        title: "Hobbes’s Moral and Political Philosophy",
        author: "Sharon A. Lloyd e Susanne Sreedhar",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min (estado de natureza)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/hobbes-moral/",
        mission: "Verifique o papel do cenário de guerra no argumento, sem tratá-lo como relato histórico simples.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
      {
        title: "Locke’s Political Philosophy",
        author: "Alex Tuckness",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min (lei natural e propriedade)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/locke-political/",
        mission: "Relacione liberdade, lei natural, consentimento e limites do governo.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Rousseau radicaliza a pergunta sobre liberdade social; Kant transforma autonomia em exigência de pensar por si e examina os limites da própria razão.",
  },
  {
    slug: "rousseau-kant-autonomia",
    number: 11,
    period: "moderna",
    kicker: "Liberdade e esclarecimento",
    title: "Rousseau e Kant: como alguém se torna autônomo?",
    shortTitle: "Rousseau, Kant e autonomia",
    duration: "40–55 min",
    difficulty: "intermediária",
    question: "Ser livre é não encontrar obstáculos ou obedecer a uma regra que se pode reconhecer como própria?",
    context: "Rousseau abre O contrato social com um paradoxo entre liberdade e correntes sociais. Kant, em 1784, descreve esclarecimento como saída da menoridade e distingue o uso público do uso privado da razão.",
    why: "Os dois autores ligam liberdade a formas de vida coletiva. A comparação evita reduzir autonomia a preferência individual e prepara debates modernos sobre história e emancipação.",
    concepts: ["liberdade", "autonomia", "vontade geral", "uso público da razão"],
    work: "O contrato social I.1; Resposta à pergunta: O que é Esclarecimento?",
    passages: [
      {
        author: "Jean-Jacques Rousseau",
        work: "O contrato social",
        locator: "livro I, capítulo 1",
        quote: "O homem nasce livre, e por toda parte encontra-se acorrentado.",
        original: "Man is born free; and everywhere he is in chains.",
        edition: "Tradução inglesa de G. D. H. Cole, Project Gutenberg, eBook 46333.",
        source: "Project Gutenberg",
        url: "https://www.gutenberg.org/ebooks/46333",
        translation: "Tradução de trabalho do projeto a partir de Cole.",
        rights: "Domínio público nos EUA segundo o Project Gutenberg; confira a jurisdição local.",
      },
      {
        author: "Immanuel Kant",
        work: "Resposta à pergunta: O que é Esclarecimento?",
        locator: "parágrafo de abertura (1784)",
        quote: "Esclarecimento é a saída do ser humano de sua menoridade autoinfligida. Ousa saber!",
        original: "Enlightenment is man's emergence from his self-incurred immaturity. Sapere aude!",
        edition: "Tradução inglesa de Lewis White Beck disponibilizada pela Wikisource.",
        source: "Wikisource",
        url: "https://en.wikisource.org/wiki/What_is_Enlightenment%3F",
        translation: "Tradução de trabalho do projeto; Unmündigkeit foi vertido por “menoridade”, termo jurídico-metafórico que pede contexto.",
        rights: "A página indica o status da tradução e disponibiliza o texto em acesso livre.",
      },
    ],
    discussed: "Rousseau pergunta por uma associação em que obedecer à lei não destrua a liberdade. Kant atribui a menoridade à incapacidade de usar o próprio entendimento sem direção alheia, mas situa o esclarecimento em condições públicas de discussão.",
    misunderstanding: "Vontade geral não é simplesmente opinião da maioria, e “pensar por si” não significa ignorar conhecimento alheio. Autonomia exige razões e instituições, não isolamento.",
    guide: "Que condições sociais permitem que a coragem de pensar produza liberdade, e não apenas exposição ao risco?",
    reflection: [
      "Uma lei pode limitar escolhas e ainda assim aumentar liberdade? Dê um caso e justifique.",
      "Qual é a diferença kantiana entre usar publicamente a razão e desobedecer a toda função institucional?",
    ],
    readings: [
      {
        title: "The Social Contract, Book I",
        author: "Jean-Jacques Rousseau",
        kind: "fonte primária",
        provider: "Project Gutenberg",
        language: "inglês",
        time: "30 min",
        difficulty: "intermediária",
        url: "https://www.gutenberg.org/ebooks/46333",
        mission: "Acompanhe como o paradoxo inicial conduz ao pacto e à vontade geral.",
        access: "domínio público nos EUA; confira a jurisdição local",
      },
      {
        title: "What is Enlightenment?",
        author: "Immanuel Kant",
        kind: "fonte primária",
        provider: "Wikisource",
        language: "inglês",
        time: "15 min",
        difficulty: "intermediária",
        url: "https://en.wikisource.org/wiki/What_is_Enlightenment%3F",
        mission: "Diferencie uso público e privado da razão antes de resumir o ensaio.",
        access: "acesso livre; tradução identificada na página",
      },
      {
        title: "The Social Contract Tradition",
        author: "Celeste Friend",
        kind: "introdução acadêmica",
        provider: "Internet Encyclopedia of Philosophy",
        language: "inglês",
        time: "20 min",
        difficulty: "intermediária",
        url: "https://iep.utm.edu/soc-cont/",
        mission: "Compare como Hobbes, Locke e Rousseau constroem o problema do consentimento.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Hegel, Marx e Nietzsche questionarão a imagem de um sujeito autônomo fora da história: instituições, trabalho, conflito e valores passam ao primeiro plano.",
  },
  {
    slug: "hegel-marx-nietzsche",
    number: 12,
    period: "contemporanea",
    kicker: "História e crítica",
    title: "Hegel, Marx e Nietzsche: pensar é também transformar?",
    shortTitle: "Hegel, Marx e Nietzsche",
    duration: "45–60 min",
    difficulty: "intermediária–avançada",
    question: "Como ideias, práticas e valores se tornam históricos — e o que a filosofia faz quando os reconhece assim?",
    context: "Os três autores não formam uma escola. Hegel pensa a verdade como desenvolvimento articulado; Marx critica um pensamento separado da prática; Nietzsche dramatiza a perda de fundamento de valores europeus.",
    why: "A leitura em contraste mostra três sentidos de crítica histórica. Ela impede que frases célebres substituam os argumentos e suas diferenças.",
    concepts: ["totalidade", "práxis", "genealogia", "niilismo"],
    work: "Fenomenologia do Espírito, prefácio §20; Teses sobre Feuerbach XI; A gaia ciência §125",
    passages: [
      {
        author: "G. W. F. Hegel",
        work: "Fenomenologia do Espírito",
        locator: "prefácio, §20",
        quote: "O verdadeiro é o todo. Mas o todo é apenas a essência que se completa por meio de seu desenvolvimento.",
        original: "The truth is the whole. The whole, however, is merely the essential nature reaching its completeness through the process of its own development.",
        edition: "Tradução inglesa histórica de J. B. Baillie disponibilizada pela Wikisource.",
        source: "Wikisource",
        url: "https://en.wikisource.org/wiki/The_Phenomenology_of_Mind/Preface",
        translation: "Tradução de trabalho do projeto a partir de Baillie; o trecho não autoriza chamar qualquer agregado de “totalidade”.",
        rights: "Página em acesso livre; verifique o status específico da edição reproduzida.",
      },
      {
        author: "Karl Marx",
        work: "Teses sobre Feuerbach",
        locator: "tese XI",
        quote: "Os filósofos apenas interpretaram o mundo de diferentes maneiras; a questão, porém, é transformá-lo.",
        original: "The philosophers have only interpreted the world, in various ways; the point is to change it.",
        edition: "Tradução inglesa de W. Lough, Progress Publishers, disponibilizada pelo Marxists Internet Archive.",
        source: "Marxists Internet Archive",
        url: "https://www.marxists.org/archive/marx/works/1845/theses/theses.htm",
        translation: "Tradução de trabalho do projeto a partir de W. Lough.",
        rights: "A página autoriza cópia e distribuição sob licença Creative Commons ShareAlike.",
      },
      {
        author: "Friedrich Nietzsche",
        work: "A gaia ciência",
        locator: "livro III, §125, “O louco”",
        quote: "Deus está morto! Deus continua morto! E nós o matamos!",
        original: "God is dead! God remains dead! And we have killed him!",
        edition: "Tradução inglesa de Thomas Common, Project Gutenberg, eBook 52881.",
        source: "Project Gutenberg",
        url: "https://www.gutenberg.org/cache/epub/52881/pg52881-images.html",
        translation: "Tradução de trabalho do projeto; leia a cena inteira do louco antes de atribuir uma tese simples à frase.",
        rights: "Domínio público nos EUA segundo o Project Gutenberg; confira a jurisdição local.",
      },
    ],
    discussed: "Hegel liga verdade ao percurso que torna uma forma inteligível; Marx insiste na atividade prática e social; Nietzsche pergunta pelas consequências da perda de um horizonte religioso compartilhado.",
    misunderstanding: "Marx não diz que interpretar seja inútil, e Nietzsche não celebra sem resto a “morte de Deus”. As duas frases descrevem tarefas e crises que exigem o contexto.",
    guide: "Uma interpretação pode transformar práticas? E uma transformação sem interpretação sabe o que está fazendo?",
    reflection: [
      "Escolha uma instituição e descreva o que muda quando a tratamos como histórica, não natural.",
      "Que novas responsabilidades surgem quando um fundamento compartilhado perde credibilidade?",
    ],
    readings: [
      {
        title: "Theses on Feuerbach",
        author: "Karl Marx",
        kind: "fonte primária",
        provider: "Marxists Internet Archive",
        language: "inglês",
        time: "10 min",
        difficulty: "intermediária",
        url: "https://www.marxists.org/archive/marx/works/1845/theses/theses.htm",
        mission: "Leia as onze teses; relacione a XI à crítica da contemplação nas anteriores.",
        access: "CC ShareAlike conforme a página",
      },
      {
        title: "The Joyful Wisdom, §125",
        author: "Friedrich Nietzsche",
        kind: "fonte primária",
        provider: "Project Gutenberg",
        language: "inglês",
        time: "12 min",
        difficulty: "intermediária",
        url: "https://www.gutenberg.org/ebooks/52881",
        mission: "Identifique quem fala, para quem fala e por que os ouvintes riem.",
        access: "domínio público nos EUA; confira a jurisdição local",
      },
      {
        title: "Hegel",
        author: "Paul Redding",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (introdução e sistema)",
        difficulty: "avançada",
        url: "https://plato.stanford.edu/entries/hegel/",
        mission: "Use a introdução para evitar reduzir “todo” a uma soma estática.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "A fenomenologia recoloca a experiência vivida no centro; existencialistas transformam esse método ao discutir mundo, corpo, liberdade e situação.",
  },
  {
    slug: "fenomenologia-existencia",
    number: 13,
    period: "contemporanea",
    kicker: "Consciência, corpo e situação",
    title: "Husserl e Beauvoir: consciência existe sem mundo?",
    shortTitle: "Fenomenologia e existência",
    duration: "40–55 min",
    difficulty: "intermediária",
    question: "A consciência é uma coisa fechada dentro de nós ou um modo de estar dirigido ao mundo e aos outros?",
    context: "Husserl chama de intencionalidade a característica de experiências serem consciência de algo. Heidegger, Sartre, Beauvoir e Merleau-Ponty transformam o campo ao pensar existência, corpo, liberdade, situação e relação com outros.",
    why: "O trecho ajuda a deixar uma imagem de mente como recipiente. O contraponto de Beauvoir lembra que experiência e liberdade são corporificadas e situadas em relações históricas.",
    concepts: ["intencionalidade", "fenômeno", "corpo vivido", "situação"],
    work: "Husserl, Ideias I, §84; diálogo com Simone de Beauvoir",
    passages: [
      {
        author: "Edmund Husserl",
        work: "Ideias para uma Fenomenologia Pura I",
        locator: "§84; Hua III/1, p. 188",
        quote: "Entendemos por intencionalidade a peculiaridade dos vividos de “serem consciência de algo”.",
        original: "Wir verstanden unter Intentionalität die Eigenheit von Erlebnissen, „Bewußtsein von etwas zu sein“.",
        edition: "Texto alemão de 1913, edição Husserliana III/1; reprodução digital do original indicada pelo Internet Archive.",
        source: "Internet Archive",
        url: "https://archive.org/details/jahrbuchfrphilo01schegoog/page/n210/mode/2up",
        translation: "Tradução direta de trabalho do projeto; Erlebnis foi vertido por “vivido”, termo técnico que não significa apenas emoção.",
        rights: "Original alemão de 1913 em acesso digital; condições do item e da plataforma se aplicam.",
      },
      {
        author: "Simone de Beauvoir",
        work: "O segundo sexo",
        locator: "volume II, parte I, capítulo 1 (1949)",
        quote: "Não se nasce mulher: torna-se mulher.",
        original: "On ne naît pas femme : on le devient.",
        edition: "Trecho breve do original francês; obra ainda protegida em diversas jurisdições.",
        source: "Registro bibliográfico — Bibliothèque nationale de France",
        url: "https://catalogue.bnf.fr/ark:/12148/cb31801059p",
        translation: "Formulação portuguesa consagrada, aqui usada como citação breve para estudo e crítica; não reproduzimos a obra.",
        rights: "Citação breve com finalidade educacional; a obra não é apresentada como conteúdo aberto.",
      },
    ],
    discussed: "Para Husserl, perceber, lembrar, desejar e julgar são modos diferentes de estar dirigido a algo. Beauvoir investiga como alguém se torna sujeito em condições corporais e sociais que já atribuem sentidos ao sexo.",
    misunderstanding: "Intencionalidade não significa “ter boa intenção”. E a frase de Beauvoir não nega o corpo; ela questiona transformar diferenças e situações em destino social necessário.",
    guide: "Se toda experiência já é relação com algo, como corpo e sociedade participam do que pode aparecer?",
    reflection: [
      "Descreva uma experiência sem explicar sua causa: para que ela se dirige e como seu objeto aparece?",
      "Que diferença há entre reconhecer condições sociais e negar a possibilidade de liberdade?",
    ],
    readings: [
      {
        title: "Ideen I, §84 (original alemão)",
        author: "Edmund Husserl",
        kind: "fonte primária",
        provider: "Internet Archive",
        language: "alemão",
        time: "10 min (passagem)",
        difficulty: "avançada",
        url: "https://archive.org/details/jahrbuchfrphilo01schegoog/page/n210/mode/2up",
        mission: "Localize Bewußtsein von etwas e observe a série perceber, julgar, valorar e desejar.",
        access: "acesso digital ao original de 1913",
      },
      {
        title: "Edmund Husserl",
        author: "Dan Zahavi",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (seções 1–3)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/husserl/",
        mission: "Diferencie intencionalidade, redução e idealismo transcendental.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
      {
        title: "Simone de Beauvoir",
        author: "Debra Bergoffen e Megan Burke",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min (ética e O segundo sexo)",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/beauvoir/",
        mission: "Situe a frase no encontro entre fenomenologia, existencialismo e opressão.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "No século XX, a linguagem deixa de parecer apenas instrumento transparente: Wittgenstein investiga sua forma lógica, enquanto Du Bois mostra como categorias sociais organizam experiência e cidadania.",
  },
  {
    slug: "linguagem-ciencia-politica",
    number: 14,
    period: "contemporanea",
    kicker: "Linguagem, ciência e raça",
    title: "Wittgenstein e Du Bois: como palavras desenham mundos?",
    shortTitle: "Linguagem, ciência e política",
    duration: "40–55 min",
    difficulty: "intermediária",
    question: "Uma proposição apenas nomeia coisas ou organiza relações — e o que acontece quando categorias organizam também vidas sociais?",
    context: "No Tractatus, Wittgenstein propõe que proposições figuram estados de coisas por uma estrutura compartilhada. Du Bois, em As almas do povo negro, nomeia a “linha de cor” como problema histórico que atravessa instituições e experiência.",
    why: "O encontro não afirma que os autores tratem do mesmo problema. Ele cria uma passagem entre análise da representação e exame crítico das categorias com que sociedades tornam relações visíveis — ou invisíveis.",
    concepts: ["proposição", "representação", "linha de cor", "dupla consciência"],
    work: "Tractatus 4.01; As almas do povo negro, “Forethought”",
    passages: [
      {
        author: "Ludwig Wittgenstein",
        work: "Tractatus Logico-Philosophicus",
        locator: "4.01",
        quote: "A proposição é uma imagem da realidade.",
        original: "Der Satz ist ein Bild der Wirklichkeit.",
        edition: "Original alemão e tradução inglesa histórica C. K. Ogden/F. P. Ramsey disponibilizados pela Wikisource.",
        source: "Wikisource",
        url: "https://en.wikisource.org/wiki/Tractatus_Logico-Philosophicus/4",
        translation: "Tradução direta de trabalho do projeto a partir do alemão.",
        rights: "Página em acesso livre; original e tradução têm situações autorais próprias conforme a jurisdição.",
      },
      {
        author: "W. E. B. Du Bois",
        work: "As almas do povo negro",
        locator: "“The Forethought” (1903)",
        quote: "O problema do século XX é o problema da linha de cor.",
        original: "The problem of the Twentieth Century is the problem of the color line.",
        edition: "Texto inglês de 1903, Project Gutenberg, eBook 408.",
        source: "Project Gutenberg",
        url: "https://www.gutenberg.org/cache/epub/408/pg408-images.html",
        translation: "Tradução de trabalho do projeto; color line designa uma relação histórica e institucional, não uma simples diferença cromática.",
        rights: "Domínio público nos EUA segundo o Project Gutenberg; confira a jurisdição local.",
      },
    ],
    discussed: "Wittgenstein compara proposição e realidade pela forma da relação, não por semelhança fotográfica. Du Bois usa uma linha conceitual e política para tornar legível uma ordem racial e, depois, descreve a experiência de olhar a si pelos olhos de uma sociedade racista.",
    misunderstanding: "“Imagem” no Tractatus não significa ilustração visual. E “linha de cor” não é previsão abstrata: o livro analisa história, educação, trabalho, segregação e experiência negra nos Estados Unidos.",
    guide: "Que relações uma descrição precisa preservar para ser informativa — e o que ela pode ocultar ao escolher suas categorias?",
    reflection: [
      "Construa duas descrições verdadeiras da mesma situação que destaquem relações diferentes.",
      "Quando uma categoria social ajuda a revelar injustiça e quando corre o risco de fixar pessoas nela?",
    ],
    readings: [
      {
        title: "Tractatus, proposições 4–4.12",
        author: "Ludwig Wittgenstein",
        kind: "fonte primária",
        provider: "Wikisource",
        language: "inglês e alemão",
        time: "25 min",
        difficulty: "avançada",
        url: "https://en.wikisource.org/wiki/Tractatus_Logico-Philosophicus/4",
        mission: "Siga imagem → sentido → verdade/falsidade; não trate 4.01 como metáfora solta.",
        access: "acesso livre; confira o status das versões",
      },
      {
        title: "The Souls of Black Folk, capítulos I e VI",
        author: "W. E. B. Du Bois",
        kind: "fonte primária",
        provider: "Project Gutenberg",
        language: "inglês",
        time: "45 min",
        difficulty: "intermediária",
        url: "https://www.gutenberg.org/ebooks/408",
        mission: "Relacione linha de cor, véu, dupla consciência e educação.",
        access: "domínio público nos EUA; confira a jurisdição local",
      },
      {
        title: "W. E. B. Du Bois",
        author: "Robert Gooding-Williams",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/dubois/",
        mission: "Veja como epistemologia, sociologia, história e filosofia política se cruzam na obra.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "O percurso termina aberto. As rotas em diálogo mostram que a cronologia europeia não esgota a história das perguntas e oferecem outros pontos de entrada responsáveis.",
  },
];

export const dialogues = [
  {
    slug: "confucio-aprender",
    routeLabel: "Leste Asiático",
    kicker: "Aprendizagem e relação",
    title: "Confúcio: aprender é também praticar?",
    shortTitle: "Confúcio e a prática",
    duration: "25–35 min",
    difficulty: "inicial",
    question: "O conhecimento transforma alguém sem prática, tempo e relação com outras pessoas?",
    context: "Os Analectos reúnem ditos e diálogos associados a Confúcio e seus discípulos, compilados ao longo de gerações. Não são um tratado escrito integralmente por uma única mão.",
    why: "A abertura liga estudo, exercício e encontro. Ela oferece um eixo de formação que não precisa ser encaixado como apêndice da cronologia europeia.",
    concepts: ["aprendizagem", "prática", "amizade", "cultivo"],
    work: "Analectos 1.1",
    passages: [
      {
        author: "Confúcio, tradição dos Analectos",
        work: "Analectos",
        locator: "1.1",
        quote: "Aprender e, no tempo devido, praticar o que se aprendeu: não é isso um prazer?",
        original: "Is it not pleasant to learn with a constant perseverance and application?",
        edition: "Tradução inglesa histórica de James Legge, The Internet Classics Archive.",
        source: "The Internet Classics Archive — MIT",
        url: "https://classics.mit.edu/Confucius/analects.1.1.html",
        translation: "Tradução de trabalho do projeto; a versão inglesa de Legge é um intermediário histórico e deve ser comparada com traduções atuais.",
        rights: "Acesso gratuito à tradução histórica; condições e direitos permanecem os da fonte.",
      },
    ],
    discussed: "O prazer de aprender aparece ligado à repetição oportuna e à chegada de amigos de longe. Conhecer não é acumular frases, mas cultivar disposições em uma comunidade.",
    misunderstanding: "Prática não significa obediência mecânica. O mesmo livro valoriza rever, julgar e combinar aprendizagem com pensamento.",
    guide: "Que tipo de prática transforma informação em caráter?",
    reflection: [
      "Escolha uma ideia deste percurso e descreva uma prática semanal que a teste.",
      "Como a presença de amigos ou interlocutores muda a qualidade do aprendizado?",
    ],
    readings: [
      {
        title: "Analects, Books 1–2",
        author: "Confúcio, na tradição dos Analectos",
        kind: "fonte primária",
        provider: "The Internet Classics Archive — MIT",
        language: "inglês",
        time: "25 min",
        difficulty: "inicial",
        url: "https://classics.mit.edu/Confucius/analects.1.1.html",
        mission: "Compare 1.1 com 2.15: aprendizagem e pensamento precisam um do outro?",
        access: "acesso gratuito; tradução histórica de James Legge",
      },
      {
        title: "Confucius",
        author: "Mark Csikszentmihalyi",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/confucius/",
        mission: "Situe os Analectos, o cultivo moral e a história de sua transmissão.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Volte a Sócrates ou Aristóteles e compare três imagens de formação: exame, hábito virtuoso e prática ritual-relacional.",
  },
  {
    slug: "dhammapada-mente",
    routeLabel: "Sul da Ásia",
    kicker: "Mente, ação e sofrimento",
    title: "Dhammapada: o que a mente faz com a experiência?",
    shortTitle: "Dhammapada e a mente",
    duration: "25–35 min",
    difficulty: "inicial",
    question: "Como disposições mentais participam do sofrimento sem tornar cada pessoa culpada por tudo que lhe acontece?",
    context: "O Dhammapada é uma coleção de versos da tradição budista preservada no cânone páli. Traduções variam porque termos como dhamma e manas condensam problemas linguísticos e doutrinais.",
    why: "O primeiro verso liga mente, fala e ação. Ele permite conversar com estoicismo e fenomenologia sem declarar as tradições equivalentes.",
    concepts: ["mente", "ação", "sofrimento", "atenção"],
    work: "Dhammapada, verso 1",
    passages: [
      {
        author: "Tradição budista",
        work: "Dhammapada",
        locator: "capítulo I, verso 1",
        quote: "Tudo o que somos é resultado do que pensamos: tem seu fundamento em nossos pensamentos e é constituído por nossos pensamentos.",
        original: "All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts.",
        edition: "Tradução inglesa de F. Max Müller, Project Gutenberg, eBook 2017.",
        source: "Project Gutenberg",
        url: "https://www.gutenberg.org/ebooks/2017",
        translation: "Tradução de trabalho a partir de Müller. É uma tradução histórica; versões atuais podem tratar os termos de outro modo.",
        rights: "Domínio público nos EUA segundo o Project Gutenberg; confira a jurisdição local.",
      },
    ],
    discussed: "O verso continua relacionando fala ou ação impura ao sofrimento. O paralelismo com o verso 2, sobre mente serena, mostra uma pedagogia de contraste.",
    misunderstanding: "O texto não deve ser usado para responsabilizar vítimas por violência, doença ou pobreza. Ele investiga a qualidade intencional de ações dentro de uma tradição ética mais ampla.",
    guide: "Como reconhecer o papel da mente sem negar condições materiais e relações de poder?",
    reflection: [
      "Que diferença existe entre um pensamento surgir e você alimentá-lo como orientação para agir?",
      "Compare o verso 1 ao Manual 5 de Epicteto: onde a aproximação ajuda e onde simplifica demais?",
    ],
    readings: [
      {
        title: "The Dhammapada, capítulos I–II",
        author: "Tradição budista; tradução de F. Max Müller",
        kind: "fonte primária",
        provider: "Project Gutenberg",
        language: "inglês",
        time: "20 min",
        difficulty: "inicial",
        url: "https://www.gutenberg.org/ebooks/2017",
        mission: "Leia os pares de versos e observe como contraste e repetição ensinam.",
        access: "domínio público nos EUA; confira a jurisdição local",
      },
      {
        title: "Buddha",
        author: "Mark Siderits",
        kind: "introdução acadêmica",
        provider: "Stanford Encyclopedia of Philosophy",
        language: "inglês",
        time: "25 min",
        difficulty: "intermediária",
        url: "https://plato.stanford.edu/entries/buddha/",
        mission: "Situe sofrimento, não-eu e caminho sem reduzir budismo a técnica de bem-estar.",
        access: "acesso gratuito; conteúdo protegido pela fonte",
      },
    ],
    relation: "Compare a análise do sofrimento com Epicuro e Epicteto, mantendo visíveis as diferenças de linguagem, prática e finalidade.",
  },
  {
    slug: "sor-juana-nisia-educacao",
    routeLabel: "América Latina e Brasil",
    kicker: "Gênero, saber e educação",
    title: "Sor Juana e Nísia Floresta: quem pode aprender e falar?",
    shortTitle: "Sor Juana, Nísia e educação",
    duration: "30–40 min",
    difficulty: "inicial",
    question: "Que contradições aparecem quando uma sociedade exige condutas das mulheres e bloqueia seu acesso à formação e à palavra pública?",
    context: "Sor Juana Inés de la Cruz, na Nova Espanha do século XVII, argumentou e escreveu em gêneros filosóficos, teológicos e poéticos. No Brasil do XIX, Nísia Floresta fez da educação das mulheres um problema público. A rota aproxima questões, não apaga épocas ou contextos.",
    why: "A seleção explicita tradições latino-americanas e brasileiras que uma linha exclusivamente europeia ocultaria. Também pergunta quem o próprio cânone autorizou a produzir conhecimento.",
    concepts: ["duplo padrão", "autoridade", "educação", "voz pública"],
    work: "Sor Juana, Redondillas; diálogo com o Opúsculo humanitário de Nísia Floresta",
    passages: [
      {
        author: "Sor Juana Inés de la Cruz",
        work: "Redondillas (“Hombres necios que acusáis”)",
        locator: "estrofe de abertura",
        quote: "Homens néscios que acusais a mulher sem razão, sem ver que sois a ocasião daquilo que censurais.",
        original: "Hombres necios que acusáis / a la mujer, sin razón, / sin ver que sois la ocasión / de lo mismo que culpáis.",
        edition: "Texto espanhol em domínio público disponibilizado pela Wikisource.",
        source: "Wikisource em espanhol",
        url: "https://es.wikisource.org/wiki/Redondillas",
        translation: "Tradução de trabalho do projeto, mantendo o encadeamento argumentativo da estrofe.",
        rights: "Original em domínio público; página da Wikisource sob CC BY-SA, com condições adicionais indicadas na fonte.",
      },
      {
        author: "Nísia Floresta",
        work: "Opúsculo humanitário",
        locator: "seção XXVI, pp. 59–60",
        quote: "Quanto mais ignorante é um povo, tanto mais fácil é a um governo absoluto exercer sobre ele o seu ilimitado poder.",
        original: "Quanto mais ignorante é um povo, tanto mais facil é a um governo absoluto exercer sobre elle o seu illimitado poder.",
        originalLanguage: "pt-BR",
        edition: "Primeira edição, Rio de Janeiro, Typographia M. A. Silva Lima, 1853; exemplar digitalizado pela BBM-USP.",
        source: "Biblioteca Brasiliana Guita e José Mindlin — USP",
        url: "https://digital.bbm.usp.br/handle/bbm/7743",
        translation: "Não há tradução: o projeto atualizou apenas a ortografia de “facil”, “elle” e “illimitado”.",
        rights: "Texto original em domínio público; reprodução digital disponibilizada pela BBM-USP sob os termos indicados no repositório.",
      },
    ],
    discussed: "A estrofe acusa uma incoerência: homens produzem condições e depois culpam mulheres pelos resultados. Nísia desloca contradição semelhante para a educação, criticando uma sociedade que limita a formação feminina e usa essa limitação como prova de inferioridade.",
    misunderstanding: "Tratar o poema apenas como “frase feminista atual” apaga seu engenho retórico, o contexto colonial e o risco intelectual de Sor Juana. Nísia também exige leitura crítica da história editorial de suas adaptações e traduções.",
    guide: "Como um grupo pode transformar a falta de oportunidade que impõe em suposta prova de incapacidade?",
    reflection: [
      "Identifique a estrutura circular da acusação na estrofe e escreva-a como duas premissas.",
      "Que instituições hoje ainda confundem acesso desigual com mérito desigual?",
    ],
    readings: [
      {
        title: "Redondillas",
        author: "Sor Juana Inés de la Cruz",
        kind: "fonte primária",
        provider: "Wikisource em espanhol",
        language: "espanhol",
        time: "10 min",
        difficulty: "inicial–intermediária",
        url: "https://es.wikisource.org/wiki/Redondillas",
        mission: "Siga as inversões e perguntas do poema; marque onde a responsabilidade muda de lado.",
        access: "original em domínio público; página CC BY-SA",
      },
      {
        title: "Opúsculo humanitário",
        author: "Nísia Floresta",
        kind: "fonte primária brasileira",
        provider: "Biblioteca Digital do Senado Federal",
        language: "português",
        time: "25 min (seleção inicial)",
        difficulty: "intermediária",
        url: "https://www2.senado.leg.br/bdsf/handle/id/658727",
        mission: "Procure como educação, costumes e poder político aparecem ligados.",
        access: "download gratuito em biblioteca pública; confira a ficha da edição",
      },
      {
        title: "O livro Direitos das mulheres e injustiça dos homens",
        author: "Isabela Candeloro Campoi",
        kind: "artigo acadêmico aberto",
        provider: "SciELO Brasil",
        language: "português",
        time: "25 min",
        difficulty: "intermediária",
        url: "https://doi.org/10.1590/S0101-90742011000200010",
        mission: "Examine a história de autoria, tradução e recepção da primeira obra de Nísia.",
        access: "acesso aberto na SciELO",
      },
    ],
    relation: "Retorne a Kant e Beauvoir: compare os sentidos de menoridade, formação e tornar-se sujeito em contextos diferentes.",
  },
];

export const sourceNetworks = [
  {
    category: "Bibliotecas e textos primários",
    items: [
      ["Perseus Digital Library — Tufts University", "https://www.perseus.tufts.edu/", "Textos greco-romanos, catálogos, edições e traduções identificadas."],
      ["Project Gutenberg", "https://www.gutenberg.org/", "E-books gratuitos; a plataforma informa quando um item está em domínio público nos EUA."],
      ["Wikisource", "https://wikisource.org/", "Transcrições colaborativas e versões livres; cada edição exige conferência própria."],
      ["Internet Archive", "https://archive.org/", "Digitalizações, empréstimos e itens abertos com condições registradas em cada página."],
      ["Biblioteca Digital do Senado Federal", "https://www2.senado.leg.br/bdsf/", "Obras brasileiras e edições públicas, incluindo a coleção Escritoras do Brasil."],
    ],
  },
  {
    category: "Referências acadêmicas de acesso gratuito",
    items: [
      ["Stanford Encyclopedia of Philosophy", "https://plato.stanford.edu/", "Artigos acadêmicos atualizados, bibliografias e autoria explícita."],
      ["Internet Encyclopedia of Philosophy", "https://iep.utm.edu/", "Introduções acadêmicas revisadas e bibliografias temáticas."],
      ["SciELO Brasil", "https://www.scielo.br/", "Periódicos acadêmicos e artigos de acesso aberto, com forte presença brasileira e latino-americana."],
      ["ANPOF", "https://anpof.org.br/", "Programas, grupos de trabalho, publicações e comunidade filosófica brasileira."],
    ],
  },
];
